version: '3.8'

services:
  agivys-db:
    image: mysql:8.0
    container_name: agivys-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: 'agivys_bd'
    volumes:
      # Esse volume garante que você não perca os dados do banco se o container for apagado
      - agivys-db-data:/var/lib/mysql

  agivys-api:
    build:
      context: ./backend/AgivysSystem.Api
      dockerfile: Dockerfile
    container_name: agivys-api-container
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      # Sobrescreve o 127.0.0.1 do appsettings apontando pro nome do container (agivys-db)
      - ConnectionStrings__DefaultConnection=Server=agivys-db;Port=3306;Database=agivys_bd;Uid=root;Pwd=${DB_PASSWORD};Charset=utf8;SslMode=none;AllowPublicKeyRetrieval=True;
      - Jwt__Key=${JWT_SECRET_KEY}
      - EmailSettings__ApiKey=${RESEND_API_KEY}
      - EmailSettings__SenderName=Theos System
      - EmailSettings__SenderEmail=contato@joederblanca.com.br
    depends_on:
      - agivys-db

volumes:
  agivys-db-data:
